### ISSUE TITLE
knexfile.ts doesn't read env files while migrating

### ISSUE THREAD

**Issue by chuksgpfr** [knex/knex#4963]
# Environment

Knex version: ^0.95.14
Database + version: mysql2 ^2.3.3
OS: MacOS

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug

I am trying to run a migration using the script `knex --knexfile src/v1/knexfile.ts migrate:latest`

But the migration keep returning error:
```
Access denied for user ''@'localhost' (using password: NO)
Error: Access denied for user ''@'localhost' (using password: NO)
```

@smorey2 @lorefnon 

knex.ts file:
```
// eslint-disable-next-line @typescript-eslint/no-var-requires
require("dotenv").config();
// Update with your config settings.
const DB_PASSWORD = process.env.DB_PASSWORD;
const DB_USERNAME = process.env.DB_USERNAME;
const DB_DATABASE = process.env.DB_DATABASE;
const DB_SOCKET = process.env.DB_SOCKET;
const DB_HOST = process.env.DB_HOST;
const DB_PORT = process.env.DB_PORT;

interface KnexConfig {
  [key: string]: object;
}

console.dir(process.env);

const knexConfig: KnexConfig = {
  development: {
    client: "mysql2",
    connection: {
      host: DB_HOST,
      port: DB_PORT,
      database: DB_DATABASE,
      user: DB_USERNAME,
      password: DB_PASSWORD,
      charset: "utf8mb4",
    },
    pool: {
      min: 2,
      max: 10,
    },
    migrations: {
      tableName: "knex_migrations",
      directory: "../../oga-shared-module/v1/migrations",
    },
  },

  staging: {
    client: "postgresql",
    connection: {
      database: "my_db",
      user: "username",
      password: "password",
    },
    pool: {
      min: 2,
      max: 10,
    },
    migrations: {
      tableName: "knex_migrations",
    },
  },

  production: {
    client: "mysql2",
    connection: {
      socketPath: DB_SOCKET,
      database: DB_DATABASE,
      user: DB_USERNAME,
      password: DB_PASSWORD,
      charset: "utf8mb4_bin",
    },
    pool: {
      min: Number(10),
      max: Number(10),
    },
    migrations: {
      tableName: "knex_migrations",
      directory: "../../oga-shared-module/v1/migrations",
    },
  },
};

export default knexConfig;

```

**Comment by NorthBlue333** [comment]
This is related to the current directory being changed during the execution. See `dotenv` doc.

```
  /**
   * Default: `path.resolve(process.cwd(), '.env')`
   *
   * Specify a custom path if your file containing environment variables is located elsewhere.
   * Can also be an array of strings, specifying multiple paths.
   *
   * example: `require('dotenv').config({ path: '/custom/path/to/.env' })`
   * example: `require('dotenv').config({ path: ['/path/to/first.env', '/path/to/second.env'] })`
   */
  path?: string | string[] | URL;
```

You have multiple options to resolve this:
* Place the knex config file on the same level as your .env files (generally in your project root)
* Wrap the knex CLI to copy the .env files before the command and remove them after the command (seems really dirty to me)
* Force set the path in the `dotenv.config()` call, like `dotenv.config({ path: path.join(__dirname, '..', '..', '.env') })` (note: if you are using ESM, please check https://stackoverflow.com/questions/46745014/alternative-for-dirname-in-node-js-when-using-es6-modules

**Comment by mercmobily** [comment]
I think we should fix it.

Here is a brief analysis of the problem.

In `bin/cli.js` (lines 48-54), when a knexfile is specified via `--knexfile` flag, Knex changes the current working directory:

```javascript
// Line 90-92
const cwd = argv.knexfile
  ? path.dirname(path.resolve(argv.knexfile))
  : process.cwd();

// Line 48-54  
if (process.cwd() !== env.cwd) {
  process.chdir(env.cwd);
  console.log('Working directory changed to', color.magenta(tildify(env.cwd)));
}
```

This happens **before** the knexfile is loaded and executed.

### 2. Dotenv Default Behavior
The `dotenv` package, by default, looks for `.env` files in the current working directory. When users have:
- `.env` file at project root
- `knexfile.ts` in a subdirectory (e.g., `src/v1/knexfile.ts`)

The working directory is changed to `src/v1/` before the knexfile loads, causing `dotenv.config()` to look for `.env` in `src/v1/` instead of the project root.

@NorthBlue333: The issue is indeed related to the fact that the current directory is changed during the execution.

The sequence of operations is:

1. CLI resolves knexfile path
2. CLI changes working directory to knexfile's directory
3. CLI loads knexfile (via `openKnexfile()`)
4. Knexfile calls `dotenv.config()` - but now in wrong directory
5. Environment variables are undefined
6. Database connection fails

This issue affects:
- **TypeScript users** - More likely to organize code in `src/` directories
- **Modern project structures** - Where config files are nested in subdirectories
- **Docker/containerized apps** - Where env files are mounted at specific paths
- **Monorepo setups** - With multiple knexfiles in different packages


### Solution 1: Document the Behavior (Minimal)

Add clear documentation explaining that:
- 
- Knex changes the working directory to the knexfile's location
- Users must adjust their `dotenv.config()` call accordingly

**Pros:** No breaking changes, immediate fix available
**Cons:** Poor developer experience, counterintuitive behavior

### Solution 2: Preserve Original CWD (Recommended)

Store the original working directory and provide it to the knexfile:

```javascript
// In cli.js
const originalCwd = process.cwd();
process.env.KNEX_ORIGINAL_CWD = originalCwd;

// Users can then use:
require('dotenv').config({ 
  path: path.join(process.env.KNEX_ORIGINAL_CWD, '.env') 
});
```

**Pros:** Non-breaking, provides escape hatch
**Cons:** Requires user awareness and code changes

### Solution 3: Delay CWD Change (Breaking)

Only change the working directory after loading the knexfile:

```javascript
async function initKnex(env, opts, useDefaultClientIfNotSpecified) {
  checkLocalModule(env);
  
  // Load config BEFORE changing directory
  env.configuration = env.configPath
    ? await openKnexfile(env.configPath)
    : mkConfigObj(opts);
    
  // THEN change directory for migrations/seeds
  if (process.cwd() !== env.cwd) {
    process.chdir(env.cwd);
  }
  // ...
}
```

**Pros:** More intuitive behaviour
**Cons:** Breaking change, might affect existing workflows

### Solution 4: Built-in Env Support (Enhancement)

Add first-class environment file support to Knex:

```javascript
// In knexfile.ts
module.exports = {
  envFile: '../../.env', // Relative to knexfile
  development: {
    client: 'mysql2',
    connection: {
      host: process.env.DB_HOST,
      // ...
    }
  }
}
```

**Pros:** Best developer experience, explicit configuration
**Cons:** New feature, requires implementation effort

## Possible path

### Phase 1: Immediate
1. **Update documentation** with clear examples of handling `.env` files
2. **Add warning** when knexfile contains `dotenv` but working directory changes
3. **Export `KNEX_ORIGINAL_CWD`** environment variable

### Phase 2: Minor Version
1. **Add `--env-file` CLI flag** to explicitly load env files:
   ```bash
   knex --env-file .env --knexfile src/knexfile.ts migrate:latest
   ```

2. **Support `.knexrc` file** for project configuration:
   ```json
   {
     "envFile": ".env",
     "knexfile": "src/v1/knexfile.ts"
   }
   ```

### Phase 3: Major Version 
1. **Change default behaviour** to load knexfile before changing directory
2. **Add explicit `changeDirectory` option** in knexfile for opt-in behavior

## Workarounds for Users (Available Today)

### Workaround 1: Explicit Path (Community Recommended)
**Recommended by @NorthBlue333** - This is the most reliable solution:
```typescript
// In knexfile.ts
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ 
  path: path.join(__dirname, '../../.env') 
});
```

For ESM modules where `__dirname` is not available:
```typescript
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ 
  path: join(__dirname, '../../.env') 
});
```

### Workaround 2: Move Knexfile
Place `knexfile.ts` at the same level as `.env`:
```
project/
  .env
  knexfile.ts
  src/
    ...
```

### Workaround 3: Wrapper Script
Create `migrate.js` (mentioned by @NorthBlue333 but not recommended):
```javascript
require('dotenv').config();
const { spawn } = require('child_process');

spawn('knex', ['--knexfile', 'src/knexfile.ts', 'migrate:latest'], {
  stdio: 'inherit',
  env: process.env
});
```
**Note**: @NorthBlue333 explicitly advises against wrapper scripts that copy/move `.env` files as they add unnecessary complexity.

### Workaround 4: Pre-load Dotenv
```bash
node -r dotenv/config $(which knex) --knexfile src/knexfile.ts migrate:latest
```

## Testing Requirements

Before implementing any solution:
1. Test with various directory structures
2. Verify backward compatibility
3. Test with different dotenv configurations
4. Ensure migrations and seeds still work correctly
5. Test in Docker containers
6. Verify monorepo compatibility

## Conclusion

This issue highlights a fundamental assumption in Knex's CLI that the knexfile should be treated as the "root" of operations. While this made sense historically, modern JavaScript projects have more complex structures. We should evolve Knex to better support these patterns while maintaining backward compatibility.

The recommended phased approach provides immediate relief to affected users while planning for a more comprehensive solution in future versions.

1. **This is a widespread issue**: The 2-year gap before root cause identification suggests many users struggled silently
2. **The fix is simple but non-obvious**: Users need explicit path configuration in `dotenv.config()`
3. **Documentation is critical**: This behavior needs prominent documentation
4. **Community solution works**: @NorthBlue333's solution has been tested and proven effective
5. **Long-term fix needed**: The current behavior violates principle of least surprise

## Action Items

- [ ] Add prominent documentation about working directory behavior
- [ ] Add example knexfiles showing proper dotenv configuration
- [ ] Consider adding warning when detecting dotenv usage without explicit path
- [ ] Evaluate changing this behavior in next major version
- [ ] Add integration tests for various project structures with .env files

**Comment by mercmobily** [comment]
I am eager to know what you guys think we should actually do.
